title: Site
columns:
  - width: 1/2
    sections:
      fields:
        type: fields
        fields:
          lastName:
            label: Last Name
            type: text
            width: 1/2
          firstName:
            label: First Name
            type: text
            width: 1/2
          byline:
            label: Byline
            type: textarea
          email:
            label: Email
            type: email
  - width: 1/2
    sections:
      pages:
        type: pages
        headline: Projects
        parent: site.find("projects")
